### PR TITLE
perf: faster HashMap with TypeId keys

### PR DESCRIPTION
**Pull request by Purpzie**
TypeIds are already hashes from the compiler, so they don't need to be hashed again. I've added a dummy hasher which just passes the TypeId through without modifying it.

For example, the `tracing-subscriber` crate does the same thing: https://github.com/tokio-rs/tracing/blob/3517552c319a22c108d423ca9a1675e632f616a3/tracing-subscriber/src/registry/extensions.rs#L12-L34

### CODE REVIEW

**Comment by SoniEx2** [comment]
relevant: https://github.com/rust-lang/rust/pull/95845

**Comment by Purpzie** [comment]
@SoniEx2 There doesn't seem to be a way to avoid that in the first place, since it's a problem in the compiler itself. Hashing the same inputs still results in the outputs being equal.

**Comment by SoniEx2** [comment]
the point is "stop relying on current implementation details".

like sure, use a faster hasher. but don't break if `TypeId` changes.

**Comment by jugglerchris** [comment]
Hi @Purpzie ,
Thanks for the contribution!
I'm certainly open to performance improvements if they're correct and significant enough to offset any extra complexity.
Have you measured the difference in performance (i.e. is hashing typeids a significant overhead)?

**Pull request closed without merging**
